"""menambahkan kolom last activate and last activity di tabel users.

Revision ID: b8b00a587bcb
Revises: 
Create Date: 2024-04-18 07:00:46.810653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b00a587bcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_activate', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('last_activity', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_activity')
        batch_op.drop_column('last_activate')

    # ### end Alembic commands ###
