"""mengubah nama kolom date di tabel twit.

Revision ID: 5fd4854dc6bb
Revises: b8b00a587bcb
Create Date: 2024-04-18 17:26:25.860999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd4854dc6bb'
down_revision = 'b8b00a587bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_post', sa.Date(), nullable=True))
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_post')

    # ### end Alembic commands ###
