"""memperbaiki beberapa struktur tabel.

Revision ID: 94c065d2f4c8
Revises: 5fd4854dc6bb
Create Date: 2024-04-18 19:08:58.242142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c065d2f4c8'
down_revision = '5fd4854dc6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('twit', schema=None) as batch_op:
        batch_op.alter_column('date_post',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('ix_twit_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=False))
        batch_op.drop_index('ix_users_id')
        batch_op.drop_column('date_birth')
        batch_op.drop_column('back_name')
        batch_op.drop_column('front_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('back_name', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date_birth', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.create_index('ix_users_id', ['id'], unique=False)
        batch_op.drop_column('birth_date')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('twit', schema=None) as batch_op:
        batch_op.create_index('ix_twit_id', ['id'], unique=False)
        batch_op.alter_column('date_post',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
